before:
  hooks:
    - go mod tidy
  
builds:
  - env:
      - CGO_ENABLED=0
    binary: kaf-relay
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})" -X "main.versionString={{ .Tag }}"

archives:
  - format: tar.gz
    files:
      - config.toml.sample
      - README.md
      - LICENSE
